-- local g_keymap = vim.keymap.set -- "Global keymap."

-- g_keymap('n', '<leader>ga', ':Git add .<CR>', { desc = 'Fu[g]itive [a]dd all files.' })
-- g_keymap('n', '<leader>gd', ':Gdiff<CR>', { desc = 'Fu[g]itive [d]iff.' })
-- g_keymap('n', '<leader>gw', ':Gwrite<CR>', { desc = 'Fu[g]itive [w]rite (stage).' })
-- g_keymap('n', '<leader>gr', ':Gread<CR>', { desc = 'Fu[g]itive [r]ead (unstage).' })
-- g_keymap('n', '<leader>gc', ':Git commit -S<CR>', { desc = 'Fu[g]itive [c]ommit.' })
-- g_keymap('n', '<leader>gp', ':Git push<CR>', { desc = 'Fu[g]itive [p]ush.' })
-- g_keymap('n', '<leader>gf', ':Git fetch<CR>', { desc = 'Fu[g]itive [f]etch.' })
-- g_keymap('n', '<leader>gP', ':Git pull<CR>', { desc = 'Fu[g]itive [P]ull.' })
-- g_keymap('n', '<leader>gR', ':Git rebase<CR>', { desc = 'Fu[g]itive [R]ebase.' })
-- g_keymap('n', '<leader>gs', ':Git<CR>', { desc = 'Fu[g]itive [s]tatus.' })
-- g_keymap('n', '<leader>gi', ':Git init<CR>', { desc = 'Fu[g]itive [I]nitiate.' })
